//
//  ApiKeyConstants.swift
//  FaceDriveDriver
//
//  Created by Subhadeep Chakraborty on 25/01/19.
//  Copyright © 2019 Dapl. All rights reserved.
//

import UIKit

class ApiKeyConstants: NSObject {
    struct kUserDefaults {
        static let DeviceToken = "DeviceToken"
        static let kDeviceToken = "kDeviceToken"
        static let kDriverDetails = "driverDetails"
        static let kIntercomLogin = "IntercomlogedIn"
        static let kTripLocation = "tripLocation"
        static let kPickUpLocation = "pickupLocation"
        static let kRegionCord = "regionCord"
        static let kStartTime = "startTime"
        static let kStartTripLattitude = "startTripLat"
        static let kStartTripLongitude = "startTripLong"
        static let kEndTripLattitude = "endTripLat"
        static let kEndTripLongitude = "endTripLong"
        static let kPickUpLattitude = "pickUpLat"
        static let kPickUpLongitude = "pickUpLong"
        static let kEndTime = "endTime"
        static let kAcceptTime = "acceptTime"
        static let kArrivedTime = "arrivedTime"
        static let kWithInTrip = "withInTrip"
        static let kUserLastLattitude = "userLastLattitude"
        static let kUserLastLongitude = "userLastLongitude"
        static let kWelcomeMessage = "welcomeMessage"
        static let kInfoMessage = "infoMessage"
        static let kPTCStatus = "ptcStatus"
        static let kCurrentEnvironment = "currentEnvironment"
        static let kCarDetailsServices = "carDetialsServices"
        static let kCarDetailsRegion = "carDetialsRegion"
        static let kCarDetailsDictionary = "carDetialsDict"
        static let kMapType = "selectedMapType"
        static let kApiResponse = "apiResponse"
    }
    
    struct PTCStatus {
        static let kProspect = "Prospect"
        static let kUploadingDocs = "Uploading 5 Docs"
        static let kUploadedDocs = "Uploaded 5 Docs"
        static let kForReview = "For Review"
        static let kEConsentSent = "eConsent sent to Candidate"
        static let kAbstractReady = "Abstract Ready"
        static let kFingerPrintsRequired = "Fingerprints Required"
        static let kAbstractRejected = "Abstract Rejected"
        static let kPTCSubmissionReady = "PTC Submission Ready"
        static let kPTCPending = "PTC Pending"
        static let kOrientationReady = "Orientation Ready"
        static let kOnRoad = "On The Road"
        static let kLicenceSuspended = "Licence suspended"
        static let kHamiltonWaitingList = "Waiting List - Hamilton"
    }
    struct CarDetails {
        static let kVehicleInfo = "vehicleInfo"
        static let kManufacturer = "manufacturer"
        static let kManufacturer_Id = "manufacturer_id"
        static let kManufacturerId = "manufacturerId"
        static let kModel = "model"
        static let kCarName = "name"
        static let kModelId = "modelId"
        static let kModel_Id = "model_id"
        static let kType_id = "type_id"
        static let kRegistrationNo = "registrationNo"
        static let kRegistration_No = "registration_no"
        static let kYearOfVehicle = "yearOfVehicle"
        static let kYear_of_vehicle = "year_of_vehicle"
        static let kSeat = "seat"
        static let kRegion_id = "region_id"
        static let kLicensePlateNo = "licensePlateNo"
        static let kLicense_plate_no = "license_plate_no"
        static let kColor = "color"
        static let kCar_Type = "car_type"
        static let kCar_Type_Id = "car_type_id"
        static let kCapacity = "capacity"
        static let kCar_Id = "car_id"
        static let kEnergyType = "energy_type"
        static let kEnergy = "energy"
        static let kEnergy_Id = "energy_id"
        static let kRegistrationDate = "registration_date"
        static let kCarDict = "carDict"
    }
    
    struct ImageType {
        static let kRight_Image = "right_image"
        static let kLeft_Image = "left_image"
        static let kRear_Image = "rear_image"
        static let kFront_Image = "front_image"
        static let kRightImage = "rightImage"
        static let kLeftImage = "leftImage"
        static let kBackImage = "backImage"
        static let kFrontImage = "frontImage"
        static let kInsuranceImage = "insuranceImage"
        static let kRegistrationImage = "registrationImage"
        static let kInspectionImage = "inspectionImage"
        static let kDocsIcon = "docsIcon"
    }
    static let kFireBasePassword = "Facedrive@123"
    
    // MARK : Login Api keys...
    static let kIsApproved = "isApproved"
    static let kRider = "rider"
    static let kLat = "lat"
    static let kLng = "lng"
    static let kType = "type"
    static let kPoint = "Point"
    static let kCoordinates = "coordinates"
    static let kMobile = "mobile"
    static let kDriverName = "name"
    static let kEmail = "email"
    static let kPassword = "password"
    static let kFirst_Name = "first_name"
    static let kFirstName = "firstName"
    static let kLast_Name = "last_name"
    static let kLastName = "lastName"
    static let kDeviceType = "device_type"
    static let kOSVersion = "os_ver"
    static let kDeviceName = "device_name"
    static let kVendorName = "vendor_name"
    static let kDeviceToken = "fcm_token"
    static let kAppVersion = "appVer"
    static let kStatus = "status"
    static let kResult = "result"
    static let kMessage = "message"
    static let kInfoMessage = "info"
    static let kSuccess = "success"
    static let kInValidSession = "is_valid_session"
    static let kImage = "image"
    static let kSocialId = "social_id"
    static let kSocialType = "social_type"
    static let kSocialLoginType = "socialLoginType"
    static let kCity = "city"
    static let kCountry = "country"
    static let kState = "state"
    static let kZoneDescription = "zoneDescription"
    static let kZoneId = "zoneId"
    static let kZoneName = "zoneName"
    static let kBookingDateTime = "booking_datetime"
    static let kXKM = "xKM"
    static let kDistanceInKM = "distance_spend_in_KM"
    static let kRegion = "region"
    static let kInfo = "info"
    static let kTotal_Earns = "total_earns"
    static let kTotal_Trips = "total_trips"
    static let kTotal_Mins = "total_mins"
    // MARK : Firebase Db keys...
    static let kid = "id"
    static let k_id = "_id"
    static let kUser_id = "user_id"
    static let kToken = "token"
    static let kAuthToken = "auth_token"
    static let kisOnline = "isOnline"
    static let kisVacant = "isVacant"
    static let klattitude = "latitude"
    static let klongitude = "longitude"
    static let kNewRequestId = "newRequestId"
    static let kServiceArea = "serviceArea"
    static let ktimeStamp = "timestamp"
    static let kTripId = "tripId"
    static let kRiderInfo = "riderInfo"
    static let kIsTripChanged = "isTripChanged"
    static let kStops = "stops"
    static let kRiderName = "name"
    static let kRiderPickup_point = "pickup_point"
    static let kRiderPickupPoint = "pickupPoint"
    static let kRiderDropPoint = "dropPoint"
    static let kRiderDrop_Point = "drop_point"
    static let kPickUpPointName = "pickupPointName"
    static let kDropPointName = "dropPointName"
    static let kDrop_Point_Name = "drop_point_name"
    static let kRiderPickupAddress = "pickupAddress"
    static let kRiderPickup_Address = "pickup_address"
    static let kRiderPick_up_address = "pick_up_address"
    static let kRiderDropOffAddress = "dropAddress"
    static let kRiderDrop_Address = "drop_address"
    static let kFirebaseTableName = "drivers"
    static let kAvgRatings = "avgRating"
    static let kRating = "rating"
    static let kFeedback = "feedback"
    static let kDriverAvgRatings = "driverAvgRating"
    static let kCountryCode = "countryCode"
    static let kCountry_code = "country_code"
    static let kMobileNumber = "mobileNo"
    static let kMobile_number = "mobile_number"
    static let kSecurityCode = "security_code"
    static let kDropPlaceID = "dropPointPlaceId"
    static let kPlace_Id = "place_id"
    static let kStop_Status = "stop_status"
    static let kDropName = "dropName"
    static let kTotal_km = "total_km"
    static let kArrived_km = "arrived_km"
    static let kTotal_time = "total_time"
    static let kArrived_time = "arrived_time"
    static let kTripDistance = "tripDistance"
    static let kProfileImage = "profileImage"
    static let kDriverPloy_Line = "driver_polyline"
    static let kFareBreakUp = "fareBreakUp"
    static let kTripTime = "tripTime"
    static let kTotalFare = "TotalFare"
    static let kChargableAmount = "chargableAmount"
    static let kBaseFare = "BaseFare"
    static let kFareForKM = "fare_for_x_km"
    static let kFareForMIN = "fare_for_y_minute"
    static let kTotalTax = "totalTax"
    static let kDiscount = "discount"
    static let kTipAmount = "tip_amount"
    static let kTrip_Fare = "trip_fare"
    static let kField_Name = "field_name"
    // MARK : Trip Status Api keys...
    static let kTripStatus = "trip_status"
    static let kTrip_id = "trip_id"
    static let kArrived = "arrived"
    static let kIntransit = "intransit"
    static let kComplete = "complete"
    static let kCompletedByRider = "completedByRider"
    static let kPending = "pending"
    static let kStartTrip = "Start Trip"
    static let kAcceptTrip = "Accept"
    static let kEndTrip = "End Trip"
    static let k_Arrived = "Arrived"
    static let kCancel = "Cancel"
    static let kConfirmStop = "Confirm Stop"
    static let kStop = "Stop"
    static let kDropOff = "Drop Off"
    static let kPickUpName = "pickupName"
    static let kPickUp = "Pick Up"
    static let kCountDownTime = "xCountdownSeconds"
    static let kDriverPayment = "driverPayment"
    static let kFinalPayment = "finalPayment"
    static let kFare = "fare"
    static let kCarbonOffsetFee = "carbonOffsetFee"
    static let kFDFees = "fdFees"
    static let kHST = "HST"
    static let kToll = "toll"
    static let kSubTotal = "subTotal"
    static let kTipsAmount = "tipAmount"
    static let kRiderRating = "riderRating"
    // MARK : Accept Reject Api keys...
    static let kNew_Request_Id = "new_request_id"
    static let kIsAccept = "is_accept"
    static let kManual = "manual"
    static let kAccepted = "accepted"
    static let kRejected = "rejected"
    static let kCancelled = "canceled"
    //    MARK : Rating Api keys....
    static let kTripRating = "trip_rating"
    static let kTripReview = "trip_review"
    //    MARK : Forgot Api Keys....
    static let kNewPassword = "new_password"
    static let kIsMobileVerified = "isMobileNumberVerified"
    static let kIsEmailVerified = "isEmailVerified"
    static let kIsScheduled = "isSchedule"
    
    //     Referal Link Api Keys -----
    static let kReferalCode = "referralCode"
    static let kCurrency = "currency"
    static let kReferalLink = "referralLink"
    static let kReferalDescription = "description"
    static let kReferalAmount = "amount"
    static let kSharedMessage = "shareMessage"
    
    //    SOSViewController Keys ------
    static let kHeaderLabel = "headerLabel"
    static let kContactNumber = "contactNumber"
    static let kStart_Date = "start_date"
    static let kEnd_Date = "end_date"
    
    static let kTitle = "title"
    static let kDocumentsTag = "documentsTag"
    static let kStatistic = "statistics"
    static let kTotalJobs = "totalJobs"
    static let kTotalDistance = "totalDistance"
    static let kHoursOnline = "hourOnline"
    static let kPageName = "pageName"
    static let kPageUrl = "pageURL"
}
